[package]
name = "wasm-jit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wasm_jit"

[dependencies]
anyhow = "1.0.78"
iced-x86 = { version = "1.20.0", features = ["code_asm"] }
memmap = "0.7.0"
