[package]
name = "wasm-jit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "wasm_jit"

[dependencies]
iced-x86 = { version = "1.14.0", features = ["code_asm"] }
memmap = "0.7.0"
